### ISSUE TITLE
PHP 7.1 error in Care Coordination Module

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#1163]
Tested on following demo:
http://www.open-emr.org/wiki/index.php/Development_Demo#Alternate_Demo_.28Alpine_3.6_-_uses_php_7.1.29

If go to Modules->Carecoordination (after install them in Modules->Manage Modules, set admin acl in Care Coordination module settings, and then logout/login), get white screen of deathwith following error in php error log:
``````
[27-Oct-2017 18:49:59 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Carecoordination\Controller\CarecoordinationController::__construct(), 0 passed in /var/www/localhost/htdocs/openemr/vendor/zendframework/zendframework/library/Zend/ServiceManager/AbstractPluginManager.php on line 207 and exactly 1 expected in /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php:40
Stack trace:
#0 /var/www/localhost/htdocs/openemr/vendor/zendframework/zendframework/library/Zend/ServiceManager/AbstractPluginManager.php(207): Carecoordination\Controller\CarecoordinationController->__construct()
#1 /var/www/localhost/htdocs/openemr/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(642): Zend\ServiceManager\AbstractPluginManager->createFromInvokable('carecoordinatio...', 'Carecoordinatio...')
#2 /var/www/localhost/htdocs/openemr/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php( in /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php on line 40
``````

**Comment by bradymiller** [comment]
fixed and submitted
