### ISSUE TITLE
PHP 7.1 error in Administration->Other->Calendar->Category Limits

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#1176]
Tested on following demo: http://www.open-emr.org/wiki/index.php/Development_Demo#Alternate_Demo_.28Alpine_3.6_-_uses_php_7.1.29

Getting white screen of death at 'Administration->Other->Calendar->Category Limits' with following php error(note there is no error/warning on php 7.0):
``````
[30-Oct-2017 18:40:59 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function postcalendar_admin_categoryLimits(), 1 passed in /var/www/localhost/htdocs/openemr/interface/main/calendar/includes/pnMod.php on line 637 and exactly 3 expected in /var/www/localhost/htdocs/openemr/interface/main/calendar/modules/PostCalendar/pnadmin.php:2185
Stack trace:
#0 /var/www/localhost/htdocs/openemr/interface/main/calendar/includes/pnMod.php(637): postcalendar_admin_categoryLimits(Array)
#1 /var/www/localhost/htdocs/openemr/interface/main/calendar/index.php(162): pnModFunc('PostCalendar', 'admin', 'categoryLimits')
#2 {main}
  thrown in /var/www/localhost/htdocs/openemr/interface/main/calendar/modules/PostCalendar/pnadmin.php on line 2185
``````

**Comment by bradymiller** [comment]
Fix with the same strategy from here: https://github.com/openemr/openemr/issues/1177

**Comment by bradymiller** [comment]
fixed
