### ISSUE TITLE
ERROR in Zend manage modules

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#1476]
Following error in PHP 7.2 when click Modules->Manage Modules along with white screen of death:
``````
[11-Mar-2018 15:00:28 UTC] PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in /var/www/html/openemr/vendor/zendframework/zendframework/library/Zend/Session/Config/SessionConfig.php on line 88
[11-Mar-2018 15:00:28 UTC] PHP Fatal error:  Uncaught Zend\Session\Exception\InvalidArgumentException: 'session.use_cookies' is not a valid sessions-related ini setting. in /var/www/html/openemr/vendor/zendframework/zendframework/library/Zend/Session/Config/SessionConfig.php:90
Stack trace:
#0 /var/www/html/openemr/vendor/zendframework/zendframework/library/Zend/Session/Config/StandardConfig.php(563): Zend\Session\Config\SessionConfig->setStorageOption('use_cookies', true)
#1 /var/www/html/openemr/vendor/zendframework/zendframework/library/Zend/Session/Config/StandardConfig.php(114): Zend\Session\Config\StandardConfig->setUseCookies(true)
#2 /var/www/html/openemr/interface/modules/zend_modules/module/Installer/Module.php(80): Zend\Session\Config\StandardConfig->setOptions(Array)
#3 [internal function]: Installer\Module->onBootstrap(Object(Zend\Mvc\MvcEvent))
#4 /var/www/html/openemr/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#5 /var/www/html/openemr/vendor/zendfram in /var/www/html/openemr/vendor/zendframework/zendframework/library/Zend/Session/Config/SessionConfig.php on line 90
``````

**Comment by bradymiller** [comment]
Received update from ZH that they are working on this fix.

**Comment by bradymiller** [comment]
fixed by @sjpadgett !!
needs some testing, so gonna leave this issue active for a little longer

**Comment by bradymiller** [comment]
testing well
