### ISSUE TITLE
Document uploads broken.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#5275]
### Describe the bug
Throws exception.
@adunsulag Probably from commit 726526a02eb4d71b2c939692c1f44f19562a53a2 looking into...

Fatal error: Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, bool given in C:\xampp\htdocs\openemr\src\Common\ORDataObject\ORDataObject.php:47 Stack trace: #0 C:\xampp\htdocs\openemr\src\Common\ORDataObject\ORDataObject.php(47): in_array('id', false) #1 C:\xampp\htdocs\openemr\library\classes\Document.class.php(772): OpenEMR\Common\ORDataObject\ORDataObject->persist() #2 C:\xampp\htdocs\openemr\library\classes\Document.class.php(1024): Document->persist() #3 C:\xampp\htdocs\openemr\controllers\C_Document.class.php(313): Document->createDocument('2', '13', '0_Alberto_Kim.x...', 'text/xml', '<?xml version="...', '', 1, false, 'C:\\xampp\\tmp\\ph...') #4 C:\xampp\htdocs\openemr\library\classes\Controller.class.php(127): C_Document->upload_action_process('2', '13') #5 C:\xampp\htdocs\openemr\controller.php(6): Controller->act(Array) #6 {main} thrown in C:\xampp\htdocs\openemr\src\Common\ORDataObject\ORDataObject.php on line 47

### To Reproduce
upload a document

**Comment by sjpadgett** [comment]
Issue is `$pkeys = $db->MetaPrimaryKeys($this->_table);` where will always be false because documents table doesn't have a primary key on my demo database and probably the testing demo database! needs to be checked.
I have no idea how I lost my primary key and may have more. Had to been during an upgrade process which is scary!

**Comment by adunsulag** [comment]
I've been uploading documents using the MU3 demo.  I'll rest to the demo database and give it a try on my machine.  I would have thought we would see this problem by now.

**Comment by sjpadgett** [comment]
Closing as not issue.
How the heck did I lose primary on document table? I saw this (another table) from an import on another DB awhile back.
At the time I concluded it had something to do with collation!

**Comment by adunsulag** [comment]
@sjpadgett Could this be a real issue?  We've seen people reporting issues of document problems on 6.1 in the forum.  Is there a way the primary key is being dropped somehow in our upgrades?

**Comment by stephenwaite** [comment]
maybe we can stick a document in the demo data

**Comment by sjpadgett** [comment]
I suspect if it is an issue(i'm saying it is) your changes where we specifically look at primary now, shows the issue so for any issues with v6.1, we'd see the exception reported.

I still believe though that weird things happen when one imports from a utf8 to utf8mb4 collated database!

**Comment by adunsulag** [comment]
@stephenwaite I just uploaded a pdf doc to a patient on the demo and it works fine.  I've broken my local install with my changes to the sql upgrade service.  Once I've got that working I'll try a document upload on the local demo (both w/o demo data and with).

**Comment by sjpadgett** [comment]
The test should be against the demo data I provided which the testing demo is based on!

**Comment by adunsulag** [comment]
@sjpadgett Wierd, I'm not sure how to setup a test from utf8 to utf8mb4 database and perhaps that is the issue.  I got my local box up and tested it against the a blank system (openemr-cmd dri) and a demo data system (openemr-cmd drid) and document uploads all appear to work.

**Comment by sjpadgett** [comment]
Well awhile back there was an upgrade issue on the forum I was going to try to get definitive answer to the collation difference however, no one wanted to answer my questions or pay attention to what I was saying. In the end user created a database as same collation and import succeeded.

However, others have done the same with no issue. So is it sequel engine version difference or types and so forth. I just keep my eye on it is best I can do. But your changes will certainly eventually bring this to light if indeed is an issue!

**Comment by stephenwaite** [comment]
the [demo data](https://github.com/openemr/openemr-devops/blob/master/docker/openemr/flex-3.15-8/utilities/demo_5_0_0_5.sql) is utf8 which gets converted to utf8mb4 I believe
