### ISSUE TITLE
CDADocumentService throws error on ccda generation with docker using port address

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5311]
The CDADocumentService class makes an HTTP call to the CareCoordination module web interface to generate a ccd document.  However, when OpenEMR is running on a docker instance and the server address is using an externally mapped port the request fails.

Example Server: https://localhost:9300 set for the oauth2 address.  However the internal docker service runs on https://localhost:443/

When a call is made to CDADocumentService->generateCCDHtml() it throws a transport exception because it can't find a service listening on port 9300 (since its on port 443 for the internal docker).  

This causes the Generate New Report button in the Patient's Report tab to fail.  I haven't tested it on portal but I imagine the View CCD button & Download CCD button have the same problem. 
![image](https://user-images.githubusercontent.com/228117/167517401-5241cd34-f2eb-4a28-b97c-785cea59c912.png)

This shouldn't impact most production sites as they are likely to be running on port 80/443 for their production environment which will map internally to the same ports on the docker install.

Here is the stack trace for the error:
Fatal error: Uncaught Symfony\Component\HttpClient\Exception\TransportException: Failed to connect to localhost port 9300 after 0 ms: Connection refused for "https://localhost:9300/interface/modules/zend_modules/public/encounterccdadispatch?combination=1&recipient=self&view=1&site=default&sent_by_app=core_api&me=DIF4HRBHQWIRMRJLcp3yJf3SkF45y9Yp62tyUz4i-r1tfS%2Cq". in /var/www/localhost/htdocs/openemr/vendor/symfony/http-client/Response/CurlResponse.php:334 Stack trace: #0 /var/www/localhost/htdocs/openemr/vendor/symfony/http-client/Response/TransportResponseTrait.php(174): Symfony\Component\HttpClient\Response\CurlResponse::perform() #1 /var/www/localhost/htdocs/openemr/vendor/symfony/http-client/Response/CommonResponseTrait.php(153): Symfony\Component\HttpClient\Response\CurlResponse::stream() #2 /var/www/localhost/htdocs/openemr/vendor/symfony/http-client/Response/TransportResponseTrait.php(53): Symfony\Component\HttpClient\Response\CurlResponse::initialize() #3 /var/www/localhost/htdocs/openemr/src/Services/CDADocumentService.php(110): Symfony\Component\HttpClient\Response\CurlResponse->getStatusCode() #4 /var/www/localhost/htdocs/openemr/ccdaservice/ccda_gateway.php(84): OpenEMR\Services\CDADocumentService->generateCCDHtml() #5 {main} Next Symfony\Component\HttpClient\Exception\TransportException: Failed to connect to localhost port 9300 after 0 ms: Connection refused for "https://localhost:9300/interface/modules/zend_modules/public/encounterccdadispatch?combination=1&recipient=self&view=1&site=default&sent_by_app=core_api&me=DIF4HRBHQWIRMRJLcp3yJf3SkF45y9Yp62tyUz4i-r1tfS%2Cq". in /var/www/localhost/htdocs/openemr/vendor/symfony/http-client/Chunk/ErrorChunk.php:65 Stack trace: #0 /var/www/localhost/htdocs/openemr/vendor/symfony/http-client/Response/CommonResponseTrait.php(154): Symfony\Component\HttpClient\Chunk\ErrorChunk->isFirst() #1 /var/www/localhost/htdocs/openemr/vendor/symfony/http-client/Response/TransportResponseTrait.php(53): Symfony\Component\HttpClient\Response\CurlResponse::initialize() #2 /var/www/localhost/htdocs/openemr/src/Services/CDADocumentService.php(110): Symfony\Component\HttpClient\Response\CurlResponse->getStatusCode() #3 /var/www/localhost/htdocs/openemr/ccdaservice/ccda_gateway.php(84): OpenEMR\Services\CDADocumentService->generateCCDHtml() #4 {main} thrown in /var/www/localhost/htdocs/openemr/vendor/symfony/http-client/Chunk/ErrorChunk.php on line 65

**Comment by adunsulag** [comment]
I planned on using this service for our FHIR $docref operation, but I'm going to just use internal events to generate the CCD and we can circle around to fix this issue later.
