### ISSUE TITLE
Previous Name save doesn't work

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#5571]
### Describe the bug

Previous Name give JS json error on save. Comes from promise receiving non json error data from ado exception Narrowed to service.

**Comment by sjpadgett** [comment]
This is weird. The binds going to ado are correct but somehow erroneous data gets injected.
binds
array (
  'pid' => '2',
  'history_type_key' => 'name_history',
  'previous_name_prefix' => 'Mrs.',
  'previous_name_first' => 'Jerry',
  'previous_name_middle' => '',
  'previous_name_last' => 'Padgett',
  'previous_name_suffix' => '',
  'previous_name_enddate' => '',
)

[27-Jun-2022 22:18:39 America/New_York] PHP Fatal error:  Uncaught ArgumentCountError: mysqli_stmt::bind_param() does not accept unknown named parameters in C:\xampp\htdocs\openemr\vendor\adodb\adodb-php\drivers\adodb-mysqli.inc.php:1302
Stack trace:
#0 C:\xampp\htdocs\openemr\vendor\adodb\adodb-php\drivers\adodb-mysqli.inc.php(1302): mysqli_stmt->bind_param('ssssssss', pid: '2', history_type_key: 'name_history', previous_name_prefix: 'Mrs.', previous_name_first: 'Jerry', previous_name_middle: '', previous_name_last: 'Padgett', previous_name_suffix: '', previous_name_enddate: '')
#1 C:\xampp\htdocs\openemr\vendor\adodb\adodb-php\adodb.inc.php(1550): ADODB_mysqli->_query('SELECT pid FROM...', Array)
#2 C:\xampp\htdocs\openemr\vendor\adodb\adodb-php\drivers\adodb-mysqli.inc.php(1150): ADOConnection->_Execute('SELECT pid FROM...', Array)
#3 C:\xampp\htdocs\openemr\library\ADODB_mysqli_log.php(27): ADODB_mysqli->execute('SELECT pid FROM...', Array)
#4 C:\xampp\htdocs\openemr\library\sql.inc(162): ADODB_mysqli_log->Execute('SELECT pid FROM...', Array, true)
#5 C:\xampp\htdocs\openemr\src\Common\Database\QueryUtils.php(148): sqlStatementThrowException('SELECT pid FROM...', Array)
#6 C:\xampp\htdocs\openemr\src\Common\Database\QueryUtils.php(65): OpenEMR\Common\Database\QueryUtils::sqlStatementThrowException('SELECT pid FROM...', Array)
#7 C:\xampp\htdocs\openemr\src\Common\Database\QueryUtils.php(75): OpenEMR\Common\Database\QueryUtils::fetchTableColumn('SELECT pid FROM...', 'pid', Array)
#8 C:\xampp\htdocs\openemr\src\Services\PatientService.php(681): OpenEMR\Common\Database\QueryUtils::fetchSingleValue('SELECT pid FROM...', 'pid', Array)
#9 C:\xampp\htdocs\openemr\library\ajax\specialty_form_ajax.php(48): OpenEMR\Services\PatientService->createPatientNameHistory('2', Array)
#10 C:\xampp\htdocs\openemr\library\ajax\specialty_form_ajax.php(26): nameHistorySave(Array)
#11 {main}
  thrown in C:\xampp\htdocs\openemr\vendor\adodb\adodb-php\drivers\adodb-mysqli.inc.php on line 1302

@adunsulag Is previous names going to be looked at tomorrow? Don't use in scenarios I know of.

**Comment by adunsulag** [comment]
@sjpadgett It is, but we handle it through the birth name which is a special case for previous name.  Data is already saved though so if this is a new bug that's been introduced it won't matter as I won't be saving any new data.

**Comment by sjpadgett** [comment]
@bradymiller This is the only thing I've come up with. Our query format is good and binds correct or I'm missing something obvious. This was working when I develop it and I assume was working when @adunsulag refactored for a service for API so maybe the adodb minor version bump apr 14 is at issue!       

 "adodb/adodb-php": "5.20.18",
        "dompdf/dompdf": "0.8.6",
        "adodb/adodb-php": "5.21.0",

**Comment by bradymiller** [comment]
Was checking out the changelog here which didn't show anything obvious: https://github.com/ADOdb/ADOdb/blob/v5.22.2/docs/changelog.md

Definitely ok to just revert to 5.22.0 and then after release 7.0 can revisit.
