### ISSUE TITLE
Anyone have trouble with docker easy dev from latest master?

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#6167]
### Describe the bug
Windows docker. This is new as it's the first time in about 3 months since I've purged and rebuilt!
```
PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'contact' already exists in /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php:1296
2023-02-01 20:37:05 Stack trace:
2023-02-01 20:37:05 #0 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(1296): mysqli_query()
2023-02-01 20:37:05 #1 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(333): Installer->execute_sql()
2023-02-01 20:37:05 #2 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(281): Installer->load_file()
2023-02-01 20:37:05 #3 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(1225): Installer->load_dumpfiles()
2023-02-01 20:37:05 #4 /var/www/localhost/htdocs/auto_configure.php(45): Installer->quick_install()
2023-02-01 20:37:05 #5 {main}
2023-02-01 20:37:05   thrown in /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php on line 1296
2023-02-01 20:37:07 PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'contact' already exists in /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php:1296
2023-02-01 20:37:07 Stack trace:
2023-02-01 20:37:07 #0 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(1296): mysqli_query()
2023-02-01 20:37:07 #1 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(333): Installer->execute_sql()
2023-02-01 20:37:07 #2 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(281): Installer->load_file()
2023-02-01 20:37:07 #3 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(1225): Installer->load_dumpfiles()
2023-02-01 20:37:07 #4 /var/www/localhost/htdocs/auto_configure.php(45): Installer->quick_install()
2023-02-01 20:37:07 #5 {main}
2023-02-01 20:37:07   thrown in /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php on line 1296
2023-02-01 20:37:07  - MySQL is still starting up and wasn't ready for connection yet
2023-02-01 20:37:07  - The Mysql credentials were incorrect
2023-02-01 20:37:09 Couldn't set up. Any of these reasons could be what's wrong:
2023-02-01 20:37:09  - You didn't spin up a MySQL container or connect your OpenEMR container to a mysql instance
2023-02-01 20:37:09  - MySQL is still starting up and wasn't ready for connection yet
2023-02-01 20:37:09  - The Mysql credentials were incorrect
2023-02-01 20:37:12 Couldn't set up. Any of these reasons could be what's wrong:
2023-02-01 20:37:12  - You didn't spin up a MySQL container or connect your OpenEMR container to a mysql instance
2023-02-01 20:37:12  - MySQL is still starting up and wasn't ready for connection yet
2023-02-01 20:37:12  - The Mysql credentials were incorrect
```

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by sjpadgett** [comment]
Looks like installer is in a loop continually creating database tables. Weird...
I can delete all tables in database and then they get reinstalled then after, back to installing tables again!!!

**Comment by bradymiller** [comment]
Just tested most recent on linux and worked ok.
rec getting most recent image
`docker pull openemr/openemr:flex`
When you tore it down, what commands did you do? (most of the time, residual shared volumes can cause weird things to happen)
`docker-compose down -v` will get rid of the shared volumes, which is what you want. If didn't do that then `docker volume prune` will get rid of unused volumes (would need to tear down the environment again before doing this).

**Comment by sjpadgett** [comment]
yeah I always prune. I did pull down new image but to no avail! Production works. Guess I'll try pulling from master instead of my local though shouldn't matter.
```
2023-02-01 22:09:20 .........+...+..+...+.......+...........+...+......+.........+......+.+..+.......+......+.......................+....+...+...+..+.......+.....+......+.......+............+..+.+...+......+......+..+...+.........+.+.........+.....+....+.........+.....+.+......+...+.....+...+....+...+...+..+...+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+......+.......+..+.+.....+.......+..+................+.........+..+.+.....+.......+......+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+................+............+..+...+.+......+.........+..+.......+...........+............+....+...+.....+.............+...............+..+..........+.....+......+.........+............................+...+......+........+...+...+.+......+...+.........+........+.......+......+..+...+.......+..+......+....+...+...+.....+..........+..............+......+....+..................+..+.....................+.+.............................+......+................+............+..................+............+..+...+...+...+....+...............+......+......+...............+.....+...+...+..................+......+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2023-02-01 22:09:21 .+..+...+....+...+...+..+.+.................+....+...+...............+...+.....+.......+..+...+.......+...+......+..............+...+....+...+...+...+...........+....+......+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+............................+..+......+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.....+.+.....+...................+......+...........+...+..........+........+...+.........+..........+.....+.+.....+............+...+....+............+.....+.+...+..+.......+..+.+...+...............+..+...+.........+......+.+......+..+..................+..........+........+......+...............+.+.........+.....+...+...+....+...+.....+...+.........+...................+..+.......+..+.+............+...............+...+..............+....+..+..........+...+..+........................+.........+....+...+..+.....................+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2023-02-01 22:09:21 -----
2023-02-01 22:10:20 Running quick setup!
2023-02-01 22:10:57 PHP Warning:  require_once(/var/www/localhost/htdocs/openemr/src/Gacl/../../vendor/adodb/adodb-php/adodb.inc.php): Failed to open stream: No such file or directory in /var/www/localhost/htdocs/openemr/src/Gacl/Gacl.php on line 34
2023-02-01 22:10:57 PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/localhost/htdocs/openemr/src/Gacl/../../vendor/adodb/adodb-php/adodb.inc.php' (include_path='.:/usr/share/php81') in /var/www/localhost/htdocs/openemr/src/Gacl/Gacl.php:34
2023-02-01 22:10:57 Stack trace:
2023-02-01 22:10:57 #0 /var/www/localhost/htdocs/openemr/vendor/composer/ClassLoader.php(571): include()
2023-02-01 22:10:57 #1 /var/www/localhost/htdocs/openemr/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
2023-02-01 22:10:57 #2 /var/www/localhost/htdocs/openemr/src/Gacl/GaclApi.php(24): Composer\Autoload\ClassLoader->loadClass()
2023-02-01 22:10:57 #3 /var/www/localhost/htdocs/openemr/vendor/composer/ClassLoader.php(571): include('...')
2023-02-01 22:10:57 #4 /var/www/localhost/htdocs/openemr/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
2023-02-01 22:10:57 #5 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(589): Composer\Autoload\ClassLoader->loadClass()
2023-02-01 22:10:57 #6 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(1250): Installer->install_gacl()
2023-02-01 22:10:57 #7 /var/www/localhost/htdocs/auto_configure.php(45): Installer->quick_install()
2023-02-01 22:10:57 #8 {main}
2023-02-01 22:10:57   thrown in /var/www/localhost/htdocs/openemr/src/Gacl/Gacl.php on line 34
2023-02-01 22:10:57 Couldn't set up. Any of these reasons could be what's wrong:
2023-02-01 22:10:57  - You didn't spin up a MySQL container or connect your OpenEMR container to a mysql instance
2023-02-01 22:10:57  - MySQL is still starting up and wasn't ready for connection yet
2023-02-01 22:10:57  - The Mysql credentials were incorrect
2023-02-01 22:10:59 PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'contact' already exists in /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php:1296
2023-02-01 22:10:59 Stack trace:
2023-02-01 22:10:59 #0 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(1296): mysqli_query()
2023-02-01 22:10:59 #1 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(333): Installer->execute_sql()
2023-02-01 22:10:59 #2 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(281): Installer->load_file()
2023-02-01 22:10:59 #3 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(1225): Installer->load_dumpfiles()
2023-02-01 22:10:59 #4 /var/www/localhost/htdocs/auto_configure.php(45): Installer->quick_install()
2023-02-01 22:10:59 #5 {main}
2023-02-01 22:10:59   thrown in /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php on line 1296
2023-02-01 22:10:59 Couldn't set up. Any of these reasons could be what's wrong:
2023-02-01 22:10:59  - You didn't spin up a MySQL container or connect your OpenEMR container to a mysql instance
2023-02-01 22:10:59  - MySQL is still starting up and wasn't ready for connection yet
2023-02-01 22:10:59  - The Mysql credentials were incorrect
2023-02-01 22:11:01 PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'contact' already exists in /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php:1296
2023-02-01 22:11:01 Stack trace:
2023-02-01 22:11:01 #0 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(1296): mysqli_query()
2023-02-01 22:11:01 #1 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(333): Installer->execute_sql()
2023-02-01 22:11:01 #2 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(281): Installer->load_file()
2023-02-01 22:11:01 #3 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(1225): Installer->load_dumpfiles()
2023-02-01 22:11:01 #4 /var/www/localhost/htdocs/auto_configure.php(45): Installer->quick_install()
2023-02-01 22:11:01 #5 {main}
2023-02-01 22:11:01   thrown in /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php on line 1296
2023-02-01 22:11:01 Couldn't set up. Any of these reasons could be what's wrong:
2023-02-01 22:11:01  - You didn't spin up a MySQL container or connect your OpenEMR container to a mysql instance
2023-02-01 22:11:01  - MySQL is still starting up and wasn't ready for connection yet
2023-02-01 22:11:01  - The Mysql credentials were incorrect
2023-02-01 22:11:03 PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'contact' already exists in /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php:1296
2023-02-01 22:11:03 Stack trace:
2023-02-01 22:11:03 #0 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(1296): mysqli_query()
2023-02-01 22:11:03 #1 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(333): Installer->execute_sql()
2023-02-01 22:11:03 #2 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(281): Installer->load_file()
2023-02-01 22:11:03 #3 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(1225): Installer->load_dumpfiles()
2023-02-01 22:11:03 #4 /var/www/localhost/htdocs/auto_configure.php(45): Installer->quick_install()
2023-02-01 22:11:03 #5 {main}
2023-02-01 22:11:03   thrown in /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php on line 1296
2023-02-01 22:11:03 Couldn't set up. Any of these reasons could be what's wrong:
2023-02-01 22:11:03  - You didn't spin up a MySQL container or connect your OpenEMR container to a mysql instance
2023-02-01 22:11:03  - MySQL is still starting up and wasn't ready for connection yet
2023-02-01 22:11:03  - The Mysql credentials were incorrect
2023-02-01 22:11:05 PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'contact' already exists in /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php:1296
2023-02-01 22:11:05 Stack trace:
2023-02-01 22:11:05 #0 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(1296): mysqli_query()
2023-02-01 22:11:05 #1 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(333): Installer->execute_sql()
2023-02-01 22:11:05 #2 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(281): Installer->load_file()
2023-02-01 22:11:05 #3 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(1225): Installer->load_dumpfiles()
2023-02-01 22:11:05 #4 /var/www/localhost/htdocs/auto_configure.php(45): Installer->quick_install()
2023-02-01 22:11:05 #5 {main}
2023-02-01 22:11:05   thrown in /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php on line 1296
2023-02-01 22:11:05 Couldn't set up. Any of these reasons could be what's wrong:
2023-02-01 22:11:05  - You didn't spin up a MySQL container or connect your OpenEMR container to a mysql instance
2023-02-01 22:11:05  - MySQL is still starting up and wasn't ready for connection yet
2023-02-01 22:11:05  - The Mysql credentials were incorrect
2023-02-01 22:11:07 PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'contact' already exists in /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php:1296
2023-02-01 22:11:07 Stack trace:
2023-02-01 22:11:07 #0 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(1296): mysqli_query()
2023-02-01 22:11:07 #1 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(333): Installer->execute_sql()
2023-02-01 22:11:07 #2 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(281): Installer->load_file()
2023-02-01 22:11:07 #3 /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php(1225): Installer->load_dumpfiles()
2023-02-01 22:11:07 #4 /var/www/localhost/htdocs/auto_configure.php(45): Installer->quick_install()
2023-02-01 22:11:07 #5 {main}
2023-02-01 22:11:07   thrown in /var/www/localhost/htdocs/openemr/library/classes/Installer.class.php on line 1296
2023-02-01 22:11:07 Couldn't set up. Any of these reasons could be what's wrong:
2023-02-01 22:11:07  - You didn't spin up a MySQL container or connect your OpenEMR container to a mysql instance
2023-02-01 22:11:07  - MySQL is still starting up and wasn't ready for connection yet
2023-02-01 22:11:07  - The Mysql credentials were incorrect

```

**Comment by sjpadgett** [comment]
I forgot you have to actually delete the public and vendor directories!
That seems weird to have to do that. Is it the same on linux?

**Comment by sjpadgett** [comment]
I thought this was tested
`
[Thu Feb 02 04:07:51.348775 2023] [php:error] [pid 40] [client 172.26.0.1:37602] PHP Fatal error:  Uncaught TypeError: OpenEMR\\Services\\LogoService::convertToWebPath(): Argument #1 ($path) must be of type string, null given, called in /var/www/localhost/htdocs/openemr/src/Services/LogoService.php on line 89 and defined in /var/www/localhost/htdocs/openemr/src/Services/LogoService.php:98\nStack trace:\n#0 /var/www/localhost/htdocs/openemr/src/Services/LogoService.php(89): OpenEMR\\Services\\LogoService->convertToWebPath()\n#1 /var/www/localhost/htdocs/openemr/interface/login/login.php(47): OpenEMR\\Services\\LogoService->getLogo()\n#2 {main}\n  thrown in /var/www/localhost/htdocs/openemr/src/Services/LogoService.php on line 98
`

**Comment by bradymiller** [comment]
As long as all the building is done within the docker, then should never have to remove vendor/public directories (this is because the docker keeps all that hidden within the docker). If you build outside the docker, then will have problems. There are some nice git command to look for and then stuff like that when it comes up:
```
git ls-files . --ignored --exclude-standard --others
git ls-files . --exclude-standard --others
git ls-files . --others
```
```
git clean -dnX
git clean -dfX
```

**Comment by bradymiller** [comment]
I think you are experiencing a bug that was meant to fix a bug (in cases where public logo is empty because docker can't see it, in order to not give fatal error was allowed to return blank but looks like still fatal error)
To fix this in your current working branch, i think will work if make these changes in your docker-compose.yml in docker/development-easy/ (which is in the current master branch):
https://github.com/openemr/openemr/commit/a48e9a5c035a4e429f5aa511cef1d654e56fae6a

**Comment by sjpadgett** [comment]
I have that commit. I pulled from master after all merges yesterday. As for deleting vendor and public, I have to do for a new install using docker-compose up. Otherwise, docker behaves perfectly on my windows 11 and I rather like it.

I still think there's a bug but can't tell as debug doesn't work anymore on my dockers! Will someone please save me from myself:)

@robertdown you use dockers on windows. Do you experience any of the issues I am? Especially a new compose up build.

**Comment by robertdown** [comment]
Hm, I will test docker down and do a fresh pull and replicate, I'm on Windows 11.

I thought I had caught the thrown exceptions surrounding this problem. Will report back my findings

**Comment by sjpadgett** [comment]
I see why it is broken on docker(at least mine) it's because of public changes where for some reason my docker won't build unless I delete public so, prob not a bug but my environment.
Still like to know why I can't build new install unless I delete vendor and public.

**Comment by stephenwaite** [comment]
huh, those directories should disappear if running `openemr-cmd down` which is `docker-compose down -v` from the `docker/development-easy` directory, remembering the other day when Ruth lost her dev enviro :grimacing:

**Comment by robertdown** [comment]
Have you always had to delete vendor and public? Or is this a recent change?

**Comment by sjpadgett** [comment]
always. When I don't install keeps creating the database tables. frustrating!

**Comment by sjpadgett** [comment]
Looks like only vendor directory needs to be deleted so I don't care. If it works this way then I'll just go with it!

**Comment by stephenwaite** [comment]
![scriptwizard](https://user-images.githubusercontent.com/5618372/216429563-2d8ac74e-13de-4c3a-89c8-e66d0fa8d1e8.gif)
