### ISSUE TITLE
sql_upgrade

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#6263]
When upgrading from 5.x to current version, running sql_upgrade reports following error trace

```
Service with name &quot;Carecoordination\Model\EncounterccdadispatchTable&quot; could not be created. Reason: Failed to execute statement. Error: Table &#039;emr7d.uuid_registry&#039; doesn&#039;t exist Statement: SELECT `uuid` FROM `uuid_registry` WHERE `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ? OR `uuid` = ?#0 /var/www/html/emr7d/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager-&gt;doCreate()
#1 /var/www/html/emr7d/interface/modules/zend_modules/module/Carecoordination/config/module.config.php(182): Laminas\ServiceManager\ServiceManager-&gt;get()
#2 /var/www/html/emr7d/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(615): Carecoordination\Module-&gt;Carecoordination\{closure}()
#3 /var/www/html/emr7d/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager-&gt;doCreate()
#4 /var/www/html/emr7d/interface/modules/zend_modules/module/Carecoordination/config/module.config.php(179): Laminas\ServiceManager\ServiceManager-&gt;get()
#5 /var/www/html/emr7d/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(615): Carecoordination\Module-&gt;Carecoordination\{closure}()
#6 /var/www/html/emr7d/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager-&gt;doCreate()
#7 /var/www/html/emr7d/interface/modules/zend_modules/module/Carecoordination/Module.php(71): Laminas\ServiceManager\ServiceManager-&gt;get()
#8 /var/www/html/emr7d/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Carecoordination\Module-&gt;onBootstrap()
#9 /var/www/html/emr7d/vendor/laminas/laminas-eventmanager/src/EventManager.php(171): Laminas\EventManager\EventManager-&gt;triggerListeners()
#10 /var/www/html/emr7d/vendor/laminas/laminas-mvc/src/Application.php(154): Laminas\EventManager\EventManager-&gt;triggerEvent()
#11 /var/www/html/emr7d/src/Core/ModulesApplication.php(61): Laminas\Mvc\Application-&gt;bootstrap()
#12 /var/www/html/emr7d/interface/globals.php(620): OpenEMR\Core\ModulesApplication-&gt;__construct()
#13 /var/www/html/emr7d/sql_upgrade.php(48): require_once(&#039;...&#039;)
#14 {main}
```

Is there specific reason for main upgrade to look at modules?
In general modules should be able to setup, maintain/upgrade and delete their own components.

**Comment by mdsupport** [comment]
If anyone encounters this issue they can force the upgrade to continue by adding the following code after line 623 in globals.php

```
        // If performing upgrade, log and continue
        // Else per prior logic terminate further processing (Why?)
        if ($GLOBALS['ongoing_sql_upgrade']) {
            error_log(errorLogEscape("Upgrade will continue."));
        } else {
            die();
        }
```
