### ISSUE TITLE
bug: swagger client authentication failed

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#6644]
### Describe the bug

can't authenticate on https://two.openemr.io/a/openemr/swagger/index.html

{"error":"invalid_client","error_description":"Client authentication failed","message":"Client authentication failed"}
```
[07-Jul-2023 22:07:05 UTC] [2023-07-07T22:07:05.326199+00:00] OpenEMR.ERROR: AuthorizationController->oauthAuthorizationFlow() OAuthServerException {"hint":"","message":"Client authentication failed","payload":{"error":"invalid_client","error_description":"Client authentication failed","message":"Client authentication failed"},"trace":"#0 /var/www/localhost/htdocs/a/openemr/vendor/league/oauth2-server/src/Grant/AbstractGrant.php(290): League\\OAuth2\\Server\\Exception\\OAuthServerException::invalidClient(Object(Nyholm\\Psr7\\ServerRequest))\n#1 /var/www/localhost/htdocs/a/openemr/src/Common/Auth/OpenIDConnect/Grant/CustomAuthCodeGrant.php(101): League\\OAuth2\\Server\\Grant\\AbstractGrant-&gt;validateRedirectUri(&#039;https://two.ope...&#039;, Object(OpenEMR\\Common\\Auth\\OpenIDConnect\\Entities\\ClientEntity), Object(Nyholm\\Psr7\\ServerRequest))\n#2 /var/www/localhost/htdocs/a/openemr/vendor/league/oauth2-server/src/Grant/AuthCodeGrant.php(281): OpenEMR\\Common\\Auth\\OpenIDConnect\\Grant\\CustomAuthCodeGrant-&gt;validateRedirectUri(&#039;https://two.ope...&#039;, Object(OpenEMR\\Common\\Auth\\OpenIDConnect\\Entities\\ClientEntity), Object(Nyholm\\Psr7\\ServerRequest))\n#3 /var/www/localhost/htdocs/a/openemr/src/Common/Auth/OpenIDConnect/Grant/CustomAuthCodeGrant.php(91): League\\OAuth2\\Server\\Grant\\AuthCodeGrant-&gt;validateAuthorizationRequest(Object(Nyholm\\Psr7\\ServerRequest))\n#4 /var/www/localhost/htdocs/a/openemr/vendor/league/oauth2-server/src/AuthorizationServer.php(163): OpenEMR\\Common\\Auth\\OpenIDConnect\\Grant\\CustomAuthCodeGrant-&gt;validateAuthorizationRequest(Object(Nyholm\\Psr7\\ServerRequest))\n#5 /var/www/localhost/htdocs/a/openemr/src/RestControllers/AuthorizationController.php(474): League\\OAuth2\\Server\\AuthorizationServer-&gt;validateAuthorizationRequest(Object(Nyholm\\Psr7\\ServerRequest))\n#6 /var/www/localhost/htdocs/a/openemr/oauth2/authorize.php(86): OpenEMR\\RestControllers\\AuthorizationController-&gt;oauthAuthorizationFlow()\n#7 {main}","redirectUri":"","errorType":"invalid_client"} []
```
### To Reproduce
register an app/client via Admin->System->API clients
choose a few scopes
![Screenshot from 2023-07-07 18-03-13](https://github.com/openemr/openemr/assets/5618372/6e9ec13f-6a6a-4098-a671-e9bd9dc59d9c)
![Screenshot from 2023-07-07 18-03-24](https://github.com/openemr/openemr/assets/5618372/561e478c-789e-4541-8730-289f3e2319ed)

then enter the generated client id and client secret into the swagger authorize
![Screenshot from 2023-07-07 18-05-38](https://github.com/openemr/openemr/assets/5618372/6593843c-9fc4-4263-a71b-11a5f270703b)
![Screenshot from 2023-07-07 18-06-28](https://github.com/openemr/openemr/assets/5618372/10752064-4cf7-4f43-a278-2696cc59a11e)

### Expected behavior
able to authenticate and try out some of the calls

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by stephenwaite** [comment]
added `https://two.openemr.io/a/openemr/swagger/oauth2-redirect.html` to `redirect_uri` field and it worked
