### ISSUE TITLE
bug: Prescription Fax fails when signature file is populated on PHP8

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#7524]
If you put a sig.png file in the interface/pic/ directory (as described in the sites/default/config.php), set the use_signature value to true
```
$GLOBALS['oer_config']['prescriptions']['use_signature'] = true;                          
```
and then try to fax the signature file it blows up with a php type safety check.
```
 PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string * int in /var/www/localhost/htdocs/openemr/vendor/rospdf/pdf-php/src/Cezpdf.php:2053\nStack trace:\n#0 /var/www/localhost/htdocs/openemr/controllers/C_Prescription.class.php(578): Cezpdf->ezImage()\n#1 /var/www/localhost/htdocs/openemr/controllers/C_Prescription.class.php(1113): C_Prescription->multiprint_footer()\n#2 /var/www/localhost/htdocs/openemr/controllers/C_Prescription.class.php(708): C_Prescription->generatePdfObjectForPrescriptionIds()\n#3 /var/www/localhost/htdocs/openemr/controllers/C_Prescription.class.php(698): C_Prescription->multiprint_action()\n#4 /var/www/localhost/htdocs/openemr/library/classes/Controller.class.php(157): C_Prescription->multiprintfax_action()\n#5 /var/www/localhost/htdocs/openemr/controller.php(6): Controller->act()\n#6 {main}\n  thrown in /var/www/localhost/htdocs/openemr/vendor/rospdf/pdf-php/src/Cezpdf.php on line 2053, referer: https://localhost:9300/controller.php?prescription&list&id=1

```

This is happening on the latest OpenEMR in master (7.0.2.1) on the easy docker development environment (php 8.3.1)

**Comment by sjpadgett** [comment]
This doesn't actually fax does it? You could add an event to call the fax module dialog.

**Comment by adunsulag** [comment]
@sjpadgett No, it just generates the pdf to do the fax.
