### ISSUE TITLE
bug: FHIR Scopes

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#7531]
### Describe the bug

Register an app then try to authorize the app

### To Reproduce

![image](https://github.com/openemr/openemr/assets/834958/e2bba363-7925-45a5-ba06-c0f5f58593b7)

1. Register app and receive client id and secret
2. go to swagger and click authorize
3. enter information

### Expected behavior

Go to login screen

### Client configuration

- Browser: Chrome
- OpenEMR version: 7.0.2 (1) with addendum
- Operating system: Ubuntu 22.04

**Comment by juggernautsei** [comment]
here is the error log
[error.log](https://github.com/user-attachments/files/16016191/error.log)

**Comment by juggernautsei** [comment]
OpenEMR.ERROR: ScopeRepository->getScopeEntityByIdentifier() request access to invalid scope {"scope":"system/AllergyIntolerance.read","validationScopes":{"nonce":{"description":"Nonce value used to detect replay attacks by third parties"},"openid":{"description":"OpenId Connect"},"fhirUser":{"description":"OpenId Connect"},"online_access":{"description":"OpenId Connect"},"offline_access":{"description":"OpenId Connect"},"launch":{"description":"OpenId Connect"},"launch/patient":{"description":"OpenId Connect"},"api:oemr":{"description":"OpenId Connect"},"api:fhir":{"description":"OpenId Connect"},"api:port":{"description":"OpenId Connect"},"profile":{"description":"OpenId Connect"},"name":{"description":"OpenId Connect"},"address":{"description":"OpenId Connect"},"given_name":{"description":"OpenId Connect"},"family_name":{"description":"OpenId Connect"},"nickname":{"description":"OpenId Connect"},"phone":{"description":"OpenId Connect"},"phone_verified":{"description":"OpenId Connect"},"email":{"description":"OpenId Connect"},"email_verified":{"description":"OpenId Connect"},"site:default":{"description":"OpenId Connect"},"patient/AllergyIntolerance.read":{"description":"OpenId Connect"},"patient/Appointment.read":{"description":"OpenId Connect"},"patient/Binary.read":{"description":"OpenId Connect"},"patient/CarePlan.read":{"description":"OpenId Connect"},"patient/CareTeam.read":{"description":"OpenId Connect"},"patient/Condition.read":{"description":"OpenId Connect"},"patient/Coverage.read":{"description":"OpenId Connect"},"patient/Device.read":{"description":"OpenId Connect"},"patient/DiagnosticReport.read":{"description":"OpenId Connect"},"patient/DocumentReference.$docref":{"description":"OpenId Connect"},"patient/DocumentReference.read":{"description":"OpenId Connect"},"patient/Encounter.read":{"description":"OpenId Connect"},"patient/Goal.read":{"description":"OpenId Connect"},"patient/Immunization.read":{"description":"OpenId Connect"},"patient/Location.read":{"description":"OpenId Connect"},"patient/Medication.read":{"description":"OpenId Connect"},"patient/MedicationRequest.read":{"description":"OpenId Connect"},"patient/Observation.read":{"description":"OpenId Connect"},"patient/Organization.read":{"description":"OpenId Connect"},"patient/Patient.read":{"description":"OpenId Connect"},"patient/Person.read":{"description":"OpenId Connect"},"patient/Practitioner.read":{"description":"OpenId Connect"},"patient/Procedure.read":{"description":"OpenId Connect"},"patient/Provenance.read":{"description":"OpenId Connect"},"user/AllergyIntolerance.read":{"description":"OpenId Connect"},"user/Appointment.read":{"description":"OpenId Connect"},"user/Binary.read":{"description":"OpenId Connect"},"user/CarePlan.read":{"description":"OpenId Connect"},"user/CareTeam.read":{"description":"OpenId Connect"},"user/Condition.read":{"description":"OpenId Connect"},"user/Coverage.read":{"description":"OpenId Connect"},"user/Device.read":{"description":"OpenId Connect"},"user/DiagnosticReport.read":{"description":"OpenId Connect"},"user/DocumentReference.$docref":{"description":"OpenId Connect"},"user/DocumentReference.read":{"description":"OpenId Connect"},"user/Encounter.read":{"description":"OpenId Connect"},"user/Goal.read":{"description":"OpenId Connect"},"user/Immunization.read":{"description":"OpenId Connect"},"user/Location.read":{"description":"OpenId Connect"},"user/Medication.read":{"description":"OpenId Connect"},"user/MedicationRequest.read":{"description":"OpenId Connect"},"user/Observation.read":{"description":"OpenId Connect"},"user/Organization.read":{"description":"OpenId Connect"},"user/Organization.write":{"description":"OpenId Connect"},"user/Patient.read":{"description":"OpenId Connect"},"user/Patient.write":{"description":"OpenId Connect"},"user/Person.read":{"description":"OpenId Connect"},"user/Practitioner.read":{"description":"OpenId Connect"},"user/Practitioner.write":{"description":"OpenId Connect"},"user/PractitionerRole.read":{"description":"OpenId Connect"},"user/Procedure.read":{"description":"OpenId Connect"},"user/Provenance.read":{"description":"OpenId Connect"},"user/ValueSet.read":{"description":"OpenId Connect"},"system/allergy.read":{"description":"OpenId Connect"},"system/allergy.write":{"description":"OpenId Connect"},"system/appointment.read":{"description":"OpenId Connect"},"system/appointment.write":{"description":"OpenId Connect"},"system/dental_issue.read":{"description":"OpenId Connect"},"system/dental_issue.write":{"description":"OpenId Connect"},"system/document.read":{"description":"OpenId Connect"},"system/document.write":{"description":"OpenId Connect"},"system/drug.read":{"description":"OpenId Connect"},"system/encounter.read":{"description":"OpenId Connect"},"system/encounter.write":{"description":"OpenId Connect"},"system/facility.read":{"description":"OpenId Connect"},"system/facility.write":{"description":"OpenId Connect"},"system/immunization.read":{"description":"OpenId Connect"},"system/insurance.read":{"description":"OpenId Connect"},"system/insurance.write":{"description":"OpenId Connect"},"system/insurance_company.read":{"description":"OpenId Connect"},"system/insurance_company.write":{"description":"OpenId Connect"},"system/insurance_type.read":{"description":"OpenId Connect"},"system/list.read":{"description":"OpenId Connect"},"system/medical_problem.read":{"description":"OpenId Connect"},"system/medical_problem.write":{"description":"OpenId Connect"},"system/medication.read":{"description":"OpenId Connect"},"system/medication.write":{"description":"OpenId Connect"},"system/message.write":{"description":"OpenId Connect"},"system/patient.read":{"description":"OpenId Connect"},"system/patient.write":{"description":"OpenId Connect"},"system/practitioner.read":{"description":"OpenId Connect"},"system/practitioner.write":{"description":"OpenId Connect"},"system/prescription.read":{"description":"OpenId Connect"},"system/procedure.read":{"description":"OpenId Connect"},"system/soap_note.read":{"description":"OpenId Connect"},"system/soap_note.write":{"description":"OpenId Connect"},"system/surgery.read":{"description":"OpenId Connect"},"system/surgery.write":{"description":"OpenId Connect"},"system/vital.read":{"description":"OpenId Connect"},"system/vital.write":{"description":"OpenId Connect"},"user/allergy.read":{"description":"OpenId Connect"},"user/allergy.write":{"description":"OpenId Connect"},"user/appointment.read":{"description":"OpenId Connect"},"user/appointment.write":{"description":"OpenId Connect"},"user/dental_issue.read":{"description":"OpenId Connect"},"user/dental_issue.write":{"description":"OpenId Connect"},"user/document.read":{"description":"OpenId Connect"},"user/document.write":{"description":"OpenId Connect"},"user/drug.read":{"description":"OpenId Connect"},"user/encounter.read":{"description":"OpenId Connect"},"user/encounter.write":{"description":"OpenId Connect"},"user/facility.read":{"description":"OpenId Connect"},"user/facility.write":{"description":"OpenId Connect"},"user/immunization.read":{"description":"OpenId Connect"},"user/insurance.read":{"description":"OpenId Connect"},"user/insurance.write":{"description":"OpenId Connect"},"user/insurance_company.read":{"description":"OpenId Connect"},"user/insurance_company.write":{"description":"OpenId Connect"},"user/insurance_type.read":{"description":"OpenId Connect"},"user/list.read":{"description":"OpenId Connect"},"user/medical_problem.read":{"description":"OpenId Connect"},"user/medical_problem.write":{"description":"OpenId Connect"},"user/medication.read":{"description":"OpenId Connect"},"user/medication.write":{"description":"OpenId Connect"},"user/message.write":{"description":"OpenId Connect"},"user/patient.read":{"description":"OpenId Connect"},"user/patient.write":{"description":"OpenId Connect"},"user/practitioner.read":{"description":"OpenId Connect"},"user/practitioner.write":{"description":"OpenId Connect"},"user/prescription.read":{"description":"OpenId Connect"},"user/
     OpenEMR.ERROR: AuthorizationController->oauthAuthorizationFlow() OAuthServerException {"hint":"Check the `system/AllergyIntolerance.read` scope","message":"The requested scope is invalid, unknown, or malformed","payload":{"error":"invalid_scope","error_description":"The requested scope is invalid, unknown, or malformed","hint":"Check the `system/AllergyIntolerance.read` scope","message":"The requested scope is invalid, unknown, or malformed"},"trace":"#0 /var/www/html/woundcare/vendor/league/oauth2-server/src/Grant/AbstractGrant.php(322): League\\\\OAuth2\\\\Server\\\\Exception\\\\OAuthServerException::invalidScope()\\n#1 /var/www/html/woundcare/vendor/league/oauth2-server/src/Grant/AuthCodeGrant.php(293): League\\\\OAuth2\\\\Server\\\\Grant\\\\AbstractGrant-&gt;validateScopes()\\n#2 /var/www/html/woundcare/src/Common/Auth/OpenIDConnect/Grant/CustomAuthCodeGrant.php(91): League\\\\OAuth2\\\\Server\\\\Grant\\\\AuthCodeGrant-&gt;validateAuthorizationRequest()\\n#3 /var/www/html/woundcare/vendor/league/oauth2-server/src/AuthorizationServer.php(163): OpenEMR\\\\Common\\\\Auth\\\\OpenIDConnect\\\\Grant\\\\CustomAuthCodeGrant-&gt;validateAuthorizationRequest()\\n#4 /var/www/html/woundcare/src/RestControllers/AuthorizationController.php(504): League\\\\OAuth2\\\\Server\\\\AuthorizationServer-&gt;validateAuthorizationRequest()\\n#5 /var/www/html/woundcare/oauth2/authorize.php(86): OpenEMR\\\\RestControllers\\\\AuthorizationController-&gt;oauthAuthorizationFlow()\\n#6 {main}","redirectUri":"https://emr.com/swagger/oauth2-redirect.html","errorType":"invalid_scope"} [], referer: https://topemr.com/swagger/

**Comment by adunsulag** [comment]
@juggernautsei How are you registering your app?  I just spun up the easy-dev docker environment with a fresh install of OpenEMR, registered the app using standard api scopes, enabled the confidential client from the GUI, and then ran swagger w/ checking all the scopes.  Everything worked fine. Do you have any custom code or something that is impacting this?

FYI here is my app registration:
```
> POST /oauth2/default/registration HTTP/1.1
> Host: localhost:9300
> User-Agent: insomnia/2021.2.2
> Cookie: XDEBUG_SESSION=PHPSTORM
> Content-Type: application/json
> Accept: */*
> Content-Length: 1190

| {
| 	"application_type": "private",
|    "redirect_uris":
|      ["https://localhost:9300/swagger/oauth2-redirect.html"],
|    "client_name": "My new test client random",
| 	"initiate_login_uri": "http://localhost:4567/inferno/oauth2/static/launch",
|    "token_endpoint_auth_method": "client_secret_post",
|    "contacts": ["me@example.org", "them@example.org"],
| 	 "scope": "openid offline_access api:oemr api:fhir api:port user/allergy.read user/allergy.write user/appointment.read user/appointment.write user/dental_issue.read user/dental_issue.write user/document.read user/document.write user/drug.read user/encounter.read user/encounter.write user/facility.read user/facility.write user/immunization.read user/insurance.read user/insurance.write user/insurance_company.read user/insurance_company.write user/insurance_type.read user/list.read user/medical_problem.read user/medical_problem.write user/medication.read user/medication.write user/message.write user/patient.read user/patient.write user/practitioner.read user/practitioner.write user/prescription.read user/procedure.read user/soap_note.read user/soap_note.write user/surgery.read user/surgery.write user/vital.read user/vital.write"
| }
```

**Comment by juggernautsei** [comment]
@adunsulag did you install patch 1 with the addendum patch?
That is where the troubles begin. Go to the demo https://demo.openemr.io/openemr/interface/smart/register-app.php site and try to register an app from the site form. You will see a js_xl undefined error at the bottom of the page even though it does create the credentials in the video attached. You will see the entire process undertaken by me. 
  
https://youtu.be/hOjCWHTlFJc

**Comment by juggernautsei** [comment]
Bump..
Has the demo site been tested for this behavior?
