### ISSUE TITLE
Upgrade database gives white page of death

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#771]
Hi
I loaded the changes in the development vesrion of my system from the official codebase and went to localhost/openemr/admin.php to upgrade the database. After clicking on "upgrade database" it gave me a white page of death

Error log is here - 
[Sat May 20 18:35:00.226973 2017] [:error] [pid 4928:tid 1972] [client ::1:58849] PHP Fatal error:  Uncaught exception 'Dotenv\\Exception\\InvalidPathException' with message 'Unable to read the environment file at C:/xampp/htdocs/openemr\\.env.' in C:\\xampp\\htdocs\\openemr\\vendor\\vlucas\\phpdotenv\\src\\Loader.php:75\nStack trace:\n#0 C:\\xampp\\htdocs\\openemr\\vendor\\vlucas\\phpdotenv\\src\\Loader.php(52): Dotenv\\Loader->ensureFileIsReadable()\n#1 C:\\xampp\\htdocs\\openemr\\vendor\\vlucas\\phpdotenv\\src\\Dotenv.php(91): Dotenv\\Loader->load()\n#2 C:\\xampp\\htdocs\\openemr\\vendor\\vlucas\\phpdotenv\\src\\Dotenv.php(48): Dotenv\\Dotenv->loadData()\n#3 C:\\xampp\\htdocs\\openemr\\interface\\globals.php(205): Dotenv\\Dotenv->load()\n#4 C:\\xampp\\htdocs\\openemr\\sql_upgrade.php(26): require_once('C:\\\\xampp\\\\htdocs...')\n#5 {main}\n  thrown in C:\\xampp\\htdocs\\openemr\\vendor\\vlucas\\phpdotenv\\src\\Loader.php on line 75, referer: http://localhost/openemr/admin.php

**Comment by arnabnaha** [comment]
Thanks @bradymiller. Your recent commit has fixed the issue
